<?php
     $_queryText = $this->getEscapedQueryText();
    ?>
    <div class="block block-list block-viewed">
    <div class="block-title">
        <strong><span><?php echo $this->__('Recommeded Products by Keyword') ?></span></strong>
    </div>
    <div class="block-content">
        <img class="etu-query-search-loading" style="margin: 20px auto;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'er/ajax-loader.gif'; ?>" />
        <ol id="etu-recommend-bysearch" class="mini-products-list">
        </ol>
        <script type="text/javascript">decorateList('etu-recommend-bysearch');</script>
    </div>
    <script id="etu-recommender" type="text/javascript">
    
    var erHostname='<?php echo Etu_Er_Helper_Data::$ER_API_SERVER;?>';
var _qquery = _qquery || [];
var _callbackList = _callbackList || [];
  var $j = jQuery.noConflict();
  function etuRecQueryCallBack(queryParams,queryResult) {    
    _callbackList.forEach(function(callback) {
        callback(queryParams,queryResult);
    });

  }
_qquery.push({
group : '<?php echo Etu_Er_Helper_Data::$ER_GROUP;?>',
cid : '<?php echo Etu_Er_Helper_Data::$ER_CID;?>',
keywords : '<?php echo $_queryText; ?>',
act : 'search',
qqueryid : 'search'
});
_callbackList.push(function (queryParams,queryResult) {
  if (queryParams.qqueryid != 'search') return;
  var productCount = <?php echo $this->getProductCount(); ?>; 
  var allItemHtml = '';
  if (queryResult.length == 0){
    $j(".etu-query-search-loading").hide();
    $j("ol#etu-recommend-bysearch").append('<li>No Results.</li>');  
  }
  for (pidx = 0; pidx < queryResult.length; pidx++){
      if (pidx >= productCount) return;   
      $j.get('<?php echo Mage::getBaseUrl();?>er/index/product?caller=search&style=slist&id='+queryResult[pidx], function( data ) {
        $j(".etu-query-search-loading").hide();
      $j("ol#etu-recommend-bysearch").append(data);      
      });
  }
});

    
    </script>
</div>

