<?php $_product = $this->getProduct();
$_caller = $this->getCaller();?>
<li class="item">
                    <?php $_imgSize = 210; ?>

                    <a href="<?php echo $_product->getProductUrl().'?eturec=1' ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" />
                    </a>
                    <div class="product-grid-info">
                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl().'?eturec=1' ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                        <?php echo $this->getPriceHtml($_product, true, '-'.$_caller) ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    </div>
                </li>